"""empty message

Revision ID: 787001338731
Revises: 0166761480f6
Create Date: 2019-07-01 10:27:22.103938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '787001338731'
down_revision = '0166761480f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('QuestionTag',
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('QuestionTag')
    # ### end Alembic commands ###
