"""empty message

Revision ID: cb8c8b1fadea
Revises: 787001338731
Create Date: 2019-07-01 10:40:17.694126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb8c8b1fadea'
down_revision = '787001338731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('QuestionTag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('QuestionTag',
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name='QuestionTag_question_id_fkey'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name='QuestionTag_tag_id_fkey')
    )
    op.drop_table('question_tag')
    # ### end Alembic commands ###
